Chart upgrade for Jitsi stable-8960-1 version
jitsi-contrib/jitsi-helm pull request #92
Opened 2023-10-30 09:23 UTC by at-platform24

with some small and some large changes.

A summary is:
- Bump up from stable-8719 to stable-8960-1
- Add /config as emptyDir, to support readOnlyRootFilesystem
- Make defaults config and cont-init scripts customize at deploy time
- Add nodePorts for Prosody and Web for restricted Kubernetes deployments
- Add example configurations, and Makefile, to test changes quickly

2023-10-30 09:26 UTC, at-platform24 commented
@spijet May you have a review please.

2023-11-24 10:14 UTC, spijet commented
Hello @at-platform24!

Sorry for the huge delay. I've added some comments to the PR, please reply when you have time.

Do I understand it right that if the custom defaults file value is empty or unset, the ConfigMap field gets populated with a stub comment, and there will be no record for that file in `volumeMounts`?

Also, can you please elaborate on the `replicas` field for Prosody? Do you want to scale it up or to replace it with an external Prosody instance(s)?

2023-11-24 11:56 UTC, at-platform24 commented
> Do I understand it right that if the custom defaults file value is empty or unset, the ConfigMap field gets populated with a stub comment, and there will be no record for that file in `volumeMounts`?

That is correct. `make template` or `make templateWithCustomDefaults` can be tried to verify the volumenMounts.

> Do you want to scale it up or to replace it with an external Prosody instance(s)?

Our use case is where we can use the external prosody instance, however, having the full config available from the helm release make external prosody configuration teaks and validation mush simpler, as well as being able to quickly stop/ start different versions during upgrades, having a safe and fast rollback path where run in-cluster prosody.

Thank you for the thoughtful review, and excellent work in maintaining this chart.

2023-11-24 12:24 UTC, spijet commented
>Our use case is where we can use the external prosody instance, however, having the full config available from the helm release make external prosody configuration teaks and validation mush simpler, as well as being able to quickly stop/ start different versions during upgrades, having a safe and fast rollback path where run in-cluster prosody.

Hmm, maybe we could add a new option that disables the provision of Prosody (the StatefulSet, Service and whatnot) while keeping all the ConfigMaps and Secrets intact? I *think* it might be easier than explaining that the `replicas` field is not supposed to be used for actually scaling Prosody. :)

2023-11-24 12:54 UTC, at-platform24 commented
Makes sense.

fixed this, along with adding a comment.
and resolved merge conflicts.

PR title is no longer relevant, but I guess that should not be a problem :smile:

2023-11-24 14:53 UTC, spijet commented
Oh, I just realized that I forgot to actually submit the review. 🤦‍♂️

Sorry, I'll update the comments and submit the review in a moment.

2023-11-24 14:55 UTC, spijet requested changes
Please refer to the in-file comments for details.

2023-11-24 14:55 UTC, spijet commented on Makefile
This makefile looks like part of a specific deployment configuration, rather than a generic thing. Can you please:

1. Change the commands in the makefile so they output the template to a file instead of stdout;
2. Add some variables to the makefile so that it'll be possible to set the release name and custom-defaults file path;

2023-11-24 18:52 UTC, at-platform24 commented on Makefile
Makefile is not part of any specific deployment, but intended to serve as a starting point for new users to possibly create their own targets or full custom Makefile, suitable for end user needs. If we end up creating multiple, somewhat opinionated, example configurations, then we can make this Makefile more generic.

Reason to send out to STDOUT is this target is supposed to be used for quick inspection of generated manifests. Possibly piping to `less` or any similar pager might be better than sending to a file.

If this sounds reasonable, we can resolve this thread and proceed with merge.

Thank you again for review and constructive feedback. Highly appreciate.

2023-11-24 18:56 UTC, at-platform24 commented
One question about version.
This changeset does not add any breaking changes from previous one, should this be a patch version bump or minor version bump?

2023-11-24 22:36 UTC, spijet commented on Makefile
I was thinking about something like this:
```Makefile
NAME := jitsi-meet-example
NAMESPACE :=
OUTFILE :=

ifeq "$(strip $(OUTFILE))" ""
OUT_FLAGS :=
else
OUT_FLAGS := > $(OUTFILE)
endif

ifeq "$(strip $(NAMESPACE))" ""
NS_FLAGS :=
else
NS_FLAGS := -n $(NAMESPACE)
endif

ifeq "$(strip $(VALUES))" ""
VAL_FLAGS :=
else
VAL_FLAGS := -f $(VALUES)
endif

template:
        echo helm template ${NS_FLAGS} ${VAL_FLAGS} --release-name ${NAME} . ${OUT_FLAGS}

package:
        echo helm package .

2023-11-24 22:44 UTC, spijet commented
> should this be a patch version bump or minor version bump?

Let's do a minor version bump (`v1.3.8` -> `v1.4.0`). This PR adds new functionality to the chart, so it makes sense to bump the minor version, even though there are no breaking changes.

2023-11-24 22:46 UTC, spijet commented
Also, since the Makefile and the custom configuration examples are not going to be rendered by Helm and applied to the k8s cluster during chart install, it makes sense to add the `Makefile` and `example-configurations` directory to the `.helmignore` file. Can you do that inside the PR, please?

2023-11-25 08:21 UTC, at-platform24 commented
All changes applied.
Feel free to make any changes needed that you find useful for the broader user community.

2023-12-16 07:48 UTC, spijet commented
Sorry for the delay. :(
I'll review the revised changes in the coming days and will let you know if everything is OK.

2024-01-22 19:51 UTC, spijet commented
Once again, sorry for the delay. The Christmas / New Year holidays are a busy period here. 😅
I'll review it now and will let you know if there's anything else we need to edit before merging.

2024-01-22 20:14 UTC, spijet requested changes
Overall looking good, I hope this review is the last before merging. :D

2024-01-22 20:14 UTC, spijet commented on charts/prosody/templates/configmaps-cont-init.yaml
> +  10-config: |
Maybe it'd make sense to rework these parts like this?
```yaml
data:
  {{- if .Values.prosody.custom.contInit }}
  {{-   range $confname,$confdata := .Values.prosody.custom.contInit }}
  {{ $confname }}: |
    {{ $confdata | nindent 4 }}
  {{-   end }}
  {{- else }}
  10-config: |
    # Using default config provided by the container image.
  {{- end }}
```

Also, note that it should be `.Values.${service}.custom`, not `.Values.custom`, since we're doing separate custom configs for every service.

2024-01-22 20:14 UTC, spijet commented on charts/prosody/templates/statefulset.yaml
> +  replicas: {{ if .Values.scaleUp }}1{{ else }}0{{end}}
Similar to the previous comment, here it should be `.Values.prosody.scaleUp` instead. Also, maybe we could go with a proper `replicaCount` knob in the values file, so people would set it to `0` as needed?

2024-01-22 20:14 UTC, spijet commented on values.yaml
> +  custom:
Also, can you please add a similar custom section to `jibri` as well? It would allow us to add custom record services and finalizers, e.g. some custom logic for S3 upload.

2024-01-22 20:34 UTC, spijet commented on charts/prosody/templates/statefulset.yaml
> +  replicas: {{ if .Values.scaleUp }}1{{ else }}0{{end}}
Or better yet, replicate the approach @emrahcom has in #99 and add a knob that enables/disables the creation of Deployment (or StatefulSet in this case) manifest and other stuff that is needed only in case when bundled Prosody is used.

2024-01-23 08:07 UTC, at-platform24 commented on charts/prosody/templates/configmaps-cont-init.yaml
> +  10-config: |
this was set in this mode since prosody is used as [subChart](https://github.com/jitsi-contrib/jitsi-helm/tree/main/charts/prosody) 

If we want to use in `.Values.${service}.custom` format, it would be better to take `custom` to [global values](https://github.com/jitsi-contrib/jitsi-helm/blob/main/values.yaml#L5).

2024-01-23 08:08 UTC, at-platform24 commented on charts/prosody/templates/statefulset.yaml
> +  replicas: {{ if .Values.scaleUp }}1{{ else }}0{{end}}
same as above.

2024-01-23 08:08 UTC, at-platform24 commented on values.yaml
> +  custom:
sure, will do perhaps later today.

2024-01-23 19:36 UTC, spijet commented on charts/prosody/templates/configmaps-cont-init.yaml
> +  10-config: |
Sorry, my brain farted very badly yesterday and I forgot that we have Prosody as a subchart. Disregard that comment. 😅

2024-01-23 20:17 UTC, spijet commented on charts/prosody/templates/statefulset.yaml
> +          defaultMode: 511
Yep, but why not `755`?

2024-01-23 21:49 UTC, spijet commented
I just merged #99, so keep an eye out for any possible conflicts and be ready to rebase if needed. 👀

2024-01-25 09:28 UTC, at-platform24 commented on charts/prosody/templates/statefulset.yaml
> +          defaultMode: 511
ahh now I understand your question...

`defaultMode` set in decimal in manifects/ helm due to json/ yaml transformations, so 511 (base 10) is 777 (base 8), which we normally use on cli shells. here are [details](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ProjectedVolumeSource.md).

755 (base 8) = 493 (base 10) would have been your suggestion, but I went for more permissive access, since by the time anyone would modify the 10-config in container, this script would have been executed already.

Just a co-incidence that 511 seems to very octal number, and caused confusion on actual permission of the script. :sweat_smile:

2024-01-25 09:36 UTC, spijet commented on charts/prosody/templates/statefulset.yaml
> +          defaultMode: 511
Aaaaah, *now* it makes sense! 🤣 

Maybe we should use an octal number then, to avoid confusion? IIRC, `defaultMode: 0755` should work and result in ConfigMap files being mounted `rwxr-xr-x` as expected. As for `777` (`rwxrwxrwx`), I *really* don't want to use it for a couple of reasons:
1. Giving worldwide write permissions on executable scripts is bad;
2. IIRC it shouldn't work, because the ConfigMap is usually mounted in R/O anyway.

2024-01-25 10:40 UTC, at-platform24 commented on charts/prosody/templates/statefulset.yaml
> +          defaultMode: 511
`defaultMode: 0755` would work as long as we limit to yaml only tools. this will break in any tool using json.

as you have pointed out, configMap will be immutable, only how the permission is seen inside the container differs, 755 or 777 does not matter.

With above in consideration, not making any changes here. If situation changes, we can make changes later.

2024-01-25 10:41 UTC, at-platform24 commented on charts/prosody/templates/statefulset.yaml
> +  replicas: {{ if .Values.scaleUp }}1{{ else }}0{{end}}
done.

2024-01-25 10:42 UTC, at-platform24 commented
> I just merged #99, so keep an eye out for any possible conflicts and be ready to rebase if needed. 👀

luckily for me no conflicts occurred on merge.
I hope we are ready for finally merging the MR.

2024-01-25 10:50 UTC, spijet commented on charts/prosody/templates/statefulset.yaml
> +          defaultMode: 511
Fair enough, I didn't take JSON format into account and forgot it cannot deal with octal numbers properly. 🤔 
But still, I would like to see these scripts mounted with `rwxr-xr-x` permissions and not think about possible problems that may pop up later unknowingly to us. Prevention is better than a cure! :)

2024-01-25 11:03 UTC, spijet commented on charts/prosody/templates/statefulset.yaml
> +  replicas: {{ if .Values.scaleUp }}1{{ else }}0{{end}}
I completely forgot about [Chart.yaml#L25](https://github.com/jitsi-contrib/jitsi-helm/blob/main/Chart.yaml#L25) — the `.Values.prosody.enabled` knob is already used for the subchart, and setting it to `false` will skip the subchart altogether (so no secrets or configmaps would be deployed).

Let's change the new knob to something like `.Values.prosody.useExternalProsody` (default `false`), akin to `useExternalJibri` and `useExternalJigasi` we already have.

2024-01-25 12:35 UTC, at-platform24 commented on charts/prosody/templates/statefulset.yaml
> +  replicas: {{ if .Values.scaleUp }}1{{ else }}0{{end}}
done.

2024-01-25 12:35 UTC, at-platform24 commented on charts/prosody/templates/statefulset.yaml
> +          defaultMode: 511
done.

2024-01-25 14:27 UTC, spijet commented
Yep, looking good to me! Merging.

Thank you for your time and once again sorry for the delays!

2024-01-25 14:27 UTC, merged