feat(chart): add jigasi
jitsi-contrib/jitsi-helm pull request #99
Opened 2024-01-22 16:39 UTC by emrahcom

This PR adds `jigasi`.

`jigasi` allows SIP clients to join Jitsi meetings and transciption. No need to publicly open ports if SIP server allows media traffics over itself.

Even some use-cases are tricky as mentioned in [this issue](https://github.com/jitsi-contrib/jitsi-helm/issues/73), there are some other uses-cases which work with simple settings.

2024-01-22 21:19 UTC, spijet requested changes
Hello @emrahcom! Thank you for your PR 🧡

I have a couple of questions/nitpicks, if you don't mind. Please check the review. :)

2024-01-22 21:19 UTC, spijet commented on templates/jigasi/xmpp-secret.yaml
> +  JIGASI_XMPP_PASSWORD: '{{ default (randAlphaNum 10) .Values.jigasi.xmpp.password | b64enc }}'
Can you please add a knob for XMPP user as well, to keep it in line with other components (like JVB)?

2024-01-22 21:19 UTC, spijet commented on templates/jigasi/xmpp-secret.yaml
> +  {{- if .Values.jigasi.enabled }}
Should we really create an empty secret if Jigasi is not used?

I don't have a solid opinion on this, since I don't quite like the approach we have with Jibri (having to uncomment the secret in `values.yaml`) either. :|

2024-01-23 06:38 UTC, emrahcom commented on templates/jigasi/xmpp-secret.yaml
> +  {{- if .Values.jigasi.enabled }}
I think that creating an empty secret is better than expecting users to update the structure of `values.yaml` (_e.g. uncommenting some lines_). If these lines are available by default, users can use the same `values.yaml` by setting values from the commandline but this is not true for the other case.

What do you think?

2024-01-23 06:43 UTC, emrahcom commented
> Do I understand it right, that Jigasi in this case doesn't need to receive any incoming connections from the outside world? How exactly is it going to communicate with the SIP server and receive incoming calls?

No, it can still receive incoming calls because it is registered SIP server and since SIP server is publicly accessible, `jigasi` is also publicly accessible through SIP server.

By the way, I tested this use-case in my deployment and it works. I created a jigasi instance by using this Helm Charts and I have no open ports for this instance but the incoming call and media traffic through SIP server work.

2024-01-23 18:33 UTC, spijet commented on templates/jigasi/xmpp-secret.yaml
> +  {{- if .Values.jigasi.enabled }}
Yep, makes sense to me. I think I'll have to rework the Jibri secret in the similar fashion.

2024-01-23 18:40 UTC, spijet commented
>By the way, I tested this use-case in my deployment and it works. I created a jigasi instance by using this Helm Charts and I have no open ports for this instance but the incoming call and media traffic through SIP server work.

Hmm, that's interesting. I was weary of trying Jigasi out myself since I don't have any SIP infrastructure around, and the official [Jitsi Meet on Docker](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker) documentation mentions something about ports 20000~20050/UDP needed for it.

2024-01-23 18:41 UTC, spijet approved these changes

2024-01-23 21:38 UTC, spijet commented
Anyway, LGTM. Let's merge it and wait for @at-platform24 to finalize #92 before tagging a new release.

2024-01-23 21:39 UTC, merged

2024-01-24 06:15 UTC, emrahcom commented
> > By the way, I tested this use-case in my deployment and it works. I created a jigasi instance by using this Helm Charts and I have no open ports for this instance but the incoming call and media traffic through SIP server work.
> 
> Hmm, that's interesting. I was weary of trying Jigasi out myself since I don't have any SIP infrastructure around, and the official [Jitsi Meet on Docker](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker) documentation mentions something about ports 20000~20050/UDP needed for it.

If the SIP server doesn't allow media traffic (RTP) over itself then these port should be publicly open on Jigasi but this is not the only option.

And `jigasi` is also used for other purpose such as transcription.

2024-11-28 11:34 UTC, Yerachmiel-Wand commented
Hi, about 
> And jigasi is also used for other purpose such as transcription.

Would you mind pointing to any docs explaining how to setup jigasi for transcription with the helm chart?
I don't need SIP, only the ability to generate transcriptions from calls, even not real time.

Thank you. :)